#pragma once

#define ERROR_OPEN_TOKEN_FAILED 1
#define ERROR_WRITE_TO_PROC_MEMORY_FAILED 16
#define ERROR_ADJUST_PERMISSIONS_FAILED 17
#define ERROR_LOCAL_ALLOC_FAILED 31
#define ERROR_SET_PID_FAILED 34
#define ERROR_UPDATE_PROC_THREAD_ATTRIBUTE_LIST_FAILED 71
#define ERROR_CREATE_REMOTE_THREAD_FAILED 72
#define ERROR_ALLOC_SECTION_FAILED 73